deployments:
  default:
    app_id:
    network:
    paratime: sapphire
    policy:
      enclaves:
      endorsements:
        - provider_instance_admin:
      fees: endorsing_node
      max_expiration: 3
